- app/config/AddTaxesHeaderCarrierForPartialsConverter.scala
- app/config/FrontendAppConfig.scala
- app/connectors/ServiceInfoPartialConnector.scala
- app/controllers/HaveYouRegisteredForTiedOilsController.scala
- app/controllers/SelectAnOilServiceController.scala
- app/controllers/actions/ServiceInfoAction.scala
- app/models/requests/DataRequest.scala
- app/models/requests/ServiceInfoRequest.scala
- app/utils/CheckYourAnswersHelper.scala
- app/utils/NextPage.scala
- app/utils/UserAnswers.scala
- app/views/govuk_wrapper.scala.html
- app/views/haveYouRegisteredForTiedOils.scala.html
- app/views/main_template.scala.html
- app/views/selectAnOilService.scala.html
- conf/application.conf
- project/FrontendBuild.scala
- test/connectors/ServiceInfoPartialConnectorSpec.scala
- test/controllers/HaveYouRegisteredForTiedOilsControllerSpec.scala
- test/controllers/SelectAnOilServiceControllerSpec.scala
- test/controllers/actions/FakeServiceInfoAction.scala
- test/utils/FakeNavigator.scala
- test/utils/NavigatorSpec.scala
- test/utils/NextPageSpec.scala
- test/views/SelectAnOilServiceViewSpec.scala
Removed the UserAnswers system in replacement for no storage of user answers.
The current URL is enough information for navigation.
Refactored the Navigator to use a type class system rather than the cacheMap of answers.
> BTA-318 | Added Service Info Banner to top of pages

- app/controllers/HaveYouRegisteredForRebatedOilsController.scala
- app/controllers/HaveYouRegisteredForTiedOilsController.scala
- app/controllers/SelectAnOilServiceController.scala
- app/utils/NextPage.scala
- app/views/haveYouRegisteredForRebatedOils.scala.html
- app/views/haveYouRegisteredForTiedOils.scala.html
- app/views/selectAnOilService.scala.html
- conf/app.routes
- conf/prod.routes
- test/controllers/HaveYouRegisteredForRebatedOilsControllerSpec.scala
- test/controllers/HaveYouRegisteredForTiedOilsControllerSpec.scala
- test/controllers/SelectAnOilServiceControllerSpec.scala
- test/utils/NextPageSpec.scala
- test/views/HaveYouRegisteredForRebatedOilsViewSpec.scala
- test/views/HaveYouRegisteredForTiedOilsViewSpec.scala
- test/views/SelectAnOilServiceViewSpec.scala
* Removed Mode from URLs/Controllers/Views
* Adjusted URL schemas to mimic business-tax-account so the only thing that needs changed is Nginx.
> BTA-318 | Adjust URLs to match BTA

- app/views/components/error_summary.scala.html
> Remove the desc from error summary to be like BTA

- .g8/BTAoptionsPage/migrations/$className__snake$.sh
- app/config/FrontendAppConfig.scala
- app/controllers/FindingYourAccountController.scala
- app/forms/FindingYourAccountFormProvider.scala
- app/identifiers/FindingYourAccountId.scala
- app/models/FindingYourAccount.scala
- app/utils/ForgottenOptions.scala
- app/utils/Navigator.scala
- app/utils/NextPage.scala
- app/utils/UrlHelper.scala
- app/views/findingYourAccount.scala.html
- app/views/govuk_wrapper.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- migrations/applied_migrations/FindingYourAccount.sh
- test/controllers/FindingYourAccountControllerSpec.scala
- test/forms/FindingYourAccountFormProviderSpec.scala
- test/utils/NavigatorSpec.scala
- test/utils/NextPageSpec.scala
- test/utils/UrlHelperSpec.scala
- test/views/FindingYourAccountViewSpec.scala
Lost credentials page created to route to government-gateway-lost-credentials-frontend
G8 template updated to change EmacHelper to UrlHelper
> BTA-375 | lost credentials journey created

- app/assets/stylesheets/addtaxesfrontend-app.scss
- app/controllers/OtherTaxesController.scala
- app/controllers/actions/AuthAction.scala
- app/models/requests/AuthenticatedRequest.scala
- app/views/organisation_only.scala.html
- conf/application.conf
- conf/messages.en
- test/controllers/OtherTaxesControllerSpec.scala
- test/controllers/actions/DataRetrievalActionSpec.scala
- test/controllers/actions/FakeAuthAction.scala
- test/controllers/other/oil/SelectAnOilServiceControllerSpec.scala
- test/views/OrganisationOnlyViewSpec.scala
> Add functionality to page that stops Individuals from

- app/controllers/OtherTaxesController.scala
- test/controllers/OtherTaxesControllerSpec.scala
*The order is now in alphabetical order
> BTA-516 | Changed the list of raio options order

- app/controllers/sa/SelectSACategoryController.scala
- test/controllers/sa/SelectSACategoryControllerSpec.scala
when already enrolled in SA and RT
> BEACD-124 | redirect to doYouWantToAddPartner

- app/views/other/oil/registerTiedOils.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/other/oil/RegisterTiedOilsViewSpec.scala
refactored messages file, updated content and refactored tests for TO
> Beacd 189 | Improve content for add Tied Oils service to BTA

- app/config/FrontendAppConfig.scala
- app/controllers/OtherTaxesController.scala
- app/models/OtherTaxes.scala
- app/utils/nextpage/OtherTaxesNextPage.scala
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test/controllers/OtherTaxesControllerSpec.scala
- test/utils/nextpage/OtherTaxesNextPageSpec.scala
- test/views/OtherTaxesViewSpec.scala
PODS-1904: Update add taxes frontend service to enable the addition of PODS enrolments for those not currently enrolled in PODS
> PODS-1904: Update add taxes frontend service to enable the addition of PODS enrolments for those not currently enrolled in PODS

- project/MicroService.scala
BTA-1451: reduced the test coverage for pipeline
> BTA-1451: reduced the test coverage for pipeline

- app/assets/stylesheets/addtaxesfrontend-app.scss
- app/views/components/input_text.scala.html
- app/views/components/submit_button.scala.html
- app/views/vat/whatIsYourVATRegNumber.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/vat/WhatIsYourVATRegNumberViewSpec.scala
BTA-1553: Content update to 'What is your VAT number' screen
> BTA-1553: Content update to 'What is your VAT number' screen

- conf/application.conf
- conf/messages.cy
- conf/messages.en
BTA-1600 : VAT imported goods - Remove brackets from 'acquired'
> BTA-1600 : VAT imported goods - Remove brackets from 'acquired'

- app/assets/stylesheets/addtaxesfrontend-app.scss
- app/views/components/input_radio.scala.html
- app/views/vat/claimRefund.scala.html
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test/views/vat/ClaimRefundViewSpec.scala
BTA-1601 : Split hint text in two line
> BTA-1601 : Split hint text in two line

- app/views/vat/doYouHaveVATRegNumber.scala.html
- test/views/vat/DoYouHaveVATRegNumberViewSpec.scala
BTA-1606:change 'have-a-vat-number' body text to hint text
> BTA-1606:change 'have-a-vat-number' body text to hint text

- app/assets/stylesheets/addtaxesfrontend-app.scss
- app/views/components/input_radio.scala.html
- app/views/vat/agriculturalFlatRateScheme.scala.html
- app/views/vat/claimRefund.scala.html
- app/views/vat/companyDivision.scala.html
- app/views/vat/distanceSelling.scala.html
- app/views/vat/importedGoods.scala.html
- app/views/vat/registerForVATOnline.scala.html
- app/views/vat/vatRegistrationException.scala.html
BTA-1598 : Update to radio button position
> BTA-1598 : Update to radio button position

- app/views/sa/enterSAUTR.scala.html
- app/views/vat/whatIsYourVATRegNumber.scala.html
- test/views/sa/EnterSAUTRViewSpec.scala
- test/views/vat/WhatIsYourVATRegNumberViewSpec.scala
BTA-1619 : Error summary for input text fields
> BTA-1619 : Error summary for input text fields

- app/assets/stylesheets/partials/_forms.scss
- app/views/components/input_radio.scala.html
- app/views/components/input_textarea.scala.html
- app/views/components/input_yes_no.scala.html
- test/views/components/InputRadioSpec.scala
- test/views/components/InputTextAreaSpec.scala
- test/views/components/InputYesNoSpec.scala
BTA-1609 : Fixed the error pattern
> BTA-1609 : Fixed the error pattern

- app/assets/stylesheets/addtaxesfrontend-app.scss
- app/views/employer/cis/ukbased/areYouContractorOrSubcontractor.scala.html
- app/views/employer/cis/ukbased/subcontractor/doYouWantToBePaidNetOrGross.scala.html
- app/views/employer/doesBusinessManagePAYE.scala.html
- app/views/other/aeoi/haveYouRegisteredAEOI.scala.html
- app/views/other/alcohol/atwd/areYouRegisteredWarehousekeeper.scala.html
- app/views/other/gambling/areYouRegisteredGTS.scala.html
- app/views/other/importexports/nes/doYouHaveCHIEFRole.scala.html
- app/views/other/land/stampduty/stampDuty.scala.html
- app/views/other/oil/haveYouRegisteredForRebatedOils.scala.html
- app/views/other/oil/haveYouRegisteredForTiedOils.scala.html
- app/views/sa/partnership/haveYouRegisteredPartnership.scala.html
- app/views/sa/trust/haveYouRegisteredTrust.scala.html
- app/views/sa/yourSaIsNotInThisAccount.scala.html
- app/views/vat/moss/alreadyRegisteredForVATMoss.scala.html
- app/views/vat/moss/noneu/haveYouRegisteredForVATMOSS.scala.html
- app/views/vat/moss/ukbased/onlineVATAccount.scala.html
- app/views/vat/moss/ukbased/registeredForVATUk.scala.html
BTA-1628 : Changed error pattern
> BTA-1628 : Changed error pattern

- app/assets/stylesheets/addtaxesfrontend-app.scss
- app/assets/stylesheets/partials/_focus.scss
- app/assets/stylesheets/partials/_palette.scss
BTA-1852 : Added focus classes
> BTA-1852 : Added focus classes

- app/views/components/error_summary.scala.html
- test/views/components/ErrorSummarySpec.scala
BTA-1862: Added role to error summary
> BTA-1862: Added role to error summary

- test/views/employer/pension/ApplyForPractitionerIDViewSpec.scala
BTA-1849: Added missing unit test
> BTA-1849: Added missing unit test

- app/views/govuk_wrapper.scala.html
- conf/messages.cy
- conf/messages.en
BTA--1871: Added region for language switcher
> BTA--1871: Added region for language switcher

- app/views/components/answer_section.scala.html
- app/views/components/error_summary.scala.html
> BTA-1910: Removed unused role

- app/assets/javascripts/error_summary_focus.js
- app/views/components/error_summary.scala.html
- app/views/govuk_wrapper.scala.html
- test/views/components/ErrorSummarySpec.scala
BTA-1863: Added focus to error summery when there is any error
> BTA-1863: Added focus to error summery when there is any error

- app/views/components/input_radio.scala.html
- app/views/components/input_text.scala.html
- app/views/components/input_textarea.scala.html
- app/views/components/input_yes_no.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/components/InputRadioSpec.scala
- test/views/components/InputTextAreaSpec.scala
- test/views/components/InputYesNoSpec.scala
BTA-1860 : Fixed hint text for radio button
> BTA-1860 : Fixed hint text for radio button

- app/views/main_template.scala.html
BTA-2116 : Added govuk init all to initialise details summary and button
> BTA-2116 : Added govuk init all to initialise details summary and button

- app/views/vat/moss/eu/registerInHomeCountry.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/vat/moss/eu/RegisterInHomeCountryViewSpec.scala
BTA-2123 : Change text for vat moss registration for eu
> BTA-2123 : Change text for vat moss registration for eu

- app/views/components/input_text.scala.html
- app/views/sa/enterSAUTR.scala.html
- app/views/vat/whatIsYourVATRegNumber.scala.html
- test/views/sa/EnterSAUTRViewSpec.scala
- test/views/vat/WhatIsYourVATRegNumberViewSpec.scala
BTA-1725 : Added heading for input text component
> BTA-1725 : Added heading for input text component

- app/controllers/employer/paye/WhatIsYourPAYEReferenceController.scala
- app/forms/employer/paye/WhatIsYourPAYEReferenceFormProvider.scala
- app/playconfig/featuretoggle/Feature.scala
- app/utils/nextpage/employer/paye/DoYouHavePAYEReferenceNextPage.scala
- app/views/employer/paye/whatIsYourPAYEReference.scala.html
- conf/app.routes
- conf/messages.cy
- conf/messages.en
- test/controllers/employer/paye/WhatIsYourPAYEReferenceControllerSpec.scala
- test/forms/employer/paye/WhatIsYourPAYEReferenceFormProviderSpec.scala
- test/utils/nextpage/employer/paye/DoYouHavePAYEReferenceNextPageSpec.scala
- test/views/employer/paye/EnterPAYEReferenceViewSpec.scala
- test/views/employer/paye/WhatIsYourPAYEReferenceViewSpec.scala
The page is not 'wired up' in the flow, as this will be handled by the optimizely experiment.
> DL-4098: Epaye enrolment checker page 2, not wired up

- conf/application.conf
- test/unit/utils/nextpage/employer/cis/uk/subcontractor/WhatTypeOfSubcontractorNextPageSpec.scala
- test/unit/utils/nextpage/sa/partnership/DoYouWantToAddPartnerNextPageSpec.scala
- test/unit/utils/nextpage/sa/partnership/HaveYouRegisteredPartnershipNextPageSpec.scala
Please merge the [acceptance tests](https://github.com/hmrc/add-taxes-acceptance-tests/pull/154) first
> DL-5042: update dfs form urls

- app/repositories/SessionRepository.scala
- conf/application.conf
- conf/logback.xml
- project/AppDependencies.scala
- test/it/connectors/SessionRepositoryISpec.scala
Reverts hmrc/add-taxes-frontend#347
> Revert "Revert "DL-5145 SessionRepository now using hmrc mongo""

- app/config/featureToggles/FeatureSwitch.scala
- app/config/featureToggles/FeatureToggleSupport.scala
- app/controllers/vat/WhatIsYourVATRegNumberController.scala
- app/utils/nextpage/vat/WhatIsYourVATRegNumberNextPage.scala
- conf/application.conf
- test/unit/controllers/ControllerSpecBase.scala
- test/unit/controllers/vat/WhatIsYourVATRegNumberControllerSpec.scala
- test/unit/utils/FeatureToggleSupportSpec.scala
https://github.com/hmrc/app-config-qa/pull/16391
https://github.com/hmrc/app-config-staging/pull/11382
https://github.com/hmrc/app-config-production/pull/16178
> [DL-8841] disable vat ETMP mandation call (behind feature switch)

- app/service/IvService.scala
- test/unit/service/IvServiceSpec.scala
> DL-15037#Comments "DL-15037 validating logged in NINO with SAUTR NINO in IV journey
